name: januscaler_flutter_ringtone_player
description: A simple player for system default ringtones, alarms and notifications
version: 1.0.1
homepage: https://github.com/januscaler/flutter_ringtone_player
repository: https://github.com/januscaler/flutter_ringtone_player

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.1 <6.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.januscaler.ringtone.player
        pluginClass: FlutterRingtonePlayerPlugin
      ios:
        pluginClass: FlutterRingtonePlayerPlugin
